/* Generated by Cython 0.29.35 */

#ifndef __PYX_HAVE__ginacsympy
#define __PYX_HAVE__ginacsympy

#include "Python.h"
#include "ginacsym.h"

#ifndef __PYX_HAVE_API__ginacsympy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int cy_call_func(PyObject *, char *, int *);

#endif /* !__PYX_HAVE_API__ginacsympy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initginacsympy(void);
#else
PyMODINIT_FUNC PyInit_ginacsympy(void);
#endif

#endif /* !__PYX_HAVE__ginacsympy */
